### ISSUE TITLE
Issues with cptac data

### ISSUE THREAD

**Issue by FFroehlich** [meyer-lab/mechanismEncoder#24]
While processing the cptac data, I ran into a couple of issues with missing/incomplete metadata:

- There are ~115k entries that don't have any `cellLine`/`timePoint`/`treatment` info, currently irgnoring those. Is there some issue with postprocessing?
- There are ~174k entries that have "Late MOLM-13" as `cellLine`, all with `timePoint`==0, is this some kind of longer experiment (there are no control/untreated conditions for that cellLine) or should this really be treated as seperate cell line/removed?
- After some filtering, I end up with about 1k entries where both `site` and `Gene` are `NaN` (I assume that entries with `site` NaN but valid `Gene` is the proteomic data, correct?), currently irgnoring those. Is there some issue with postprocessing?
- Some entries list `Trametinib Withdrawn` as treatment. Do we have any additional information about experimental setup?

**Comment by sgosline** [comment]
First off, I think you're referring to the cell line data, not the CPTAC data, so I'm assuming that's what you meant?
Quick answers: 
- the samples without clinical/experimental info: those are other controls with no actual data corresponding to those, used for internal proteomics normalization, so feel free to ignore those.
- time point of 0 means untreated. The logratio is the value relative to the internal control, NOT the control time point. To get relative change from the control you need to subtract the t0 value.
- Yes, they are NaN because the gene does not match in swissprot, again you can discard.
- Hmm, i thought these were in a diffferent table...i might have uploaded them to this table by accident?  Anyway, they are cells that were grown in the presence of tram but then the tram was removed before measured. 
Issues 1 and 3 aren't in table `syn22255396`, which has the cell line time course data, but rather other experiments.  .

**Comment by sgosline** [comment]
As far as the data update goes - it hasn't fully be normalized/batch corrected. I hope to have it in my hands by the middle of next week (depending on how many batch effects there are).

**Comment by sgosline** [comment]
Get this - we "found" a dataset from 2018 that has never been used! It might be published with an existing paper, but either way we can use it right away. We have MOLM14 cells treated with gilteritinib and DMSO after 30 minutes and 3hrs. It looks like there are two sets of cells. 
Phospho data is here: https://www.synapse.org/#!Synapse:syn24189487/tables/
"site-corrected" data is here: https://www.synapse.org/#!Synapse:syn24189489/tables/
This second table matches the site-correction in the patient data. 

I did this late last night, and there are some typos in the table, I will fix them soon.

**Comment by sgosline** [comment]
Typos are fixed, and zero values are removed.
